version: '3'

services:
  django:
    build: .
    command: bash -c "poetry run python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - REDIS_HOST=redis
    restart: always

  celery:
    build:
      context: .
      dockerfile: Celery.Dockerfile
    command: poetry run celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

#  nginx:
#    build:
#      context: .
#      dockerfile: Nginx.Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - "80:80"
#    depends_on:
#      - django

volumes:
  postgres_data: