# Generated by Django 5.0.4 on 2024-04-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
    ]
